function gen_layer_menu(layers)
h = 300;
w = 150;
fbcolor = [1 1 1];
fig2 = figure(... 
    'units','pixels',...
    'color',fbcolor,...
    'position',[0 0 w h]);
controls = [];
inc = h/length(layers);
ph = h;
pw = w;
pnl = uipanel(...
    'parent',fig2,...
    'backgroundcolor',fbcolor,...
    'units','pixels',...
    'title','LAYERS',...
    'fontname','sketchflow print',...
    'fontsize',12,...
    'position',[0 h-ph pw ph]);
for k = 1:length(layers)
    x = uicontrol(...
        'fontsize',12,...
        'fontname','sketchflow print',...        
        'backgroundcolor',fbcolor,...
        'parent',pnl,...
        'units','pixels',...
        'style',...
        'checkbox',...
        'string',...
        layers(k).name,...
        'userdata',layers(k),...
        'callback',@callback,...
        'value',layers(k).IsVisible());
    set(x,'position',[20 ph-20*(k+2) 100 20]);
    controls = [controls, x];
end

end


function callback(checkbox, eventdata)
L = get(checkbox,'userdata');
switch(get(checkbox,'value'))
    case 0
        L.SetVisibility('off');
    case 1
        L.SetVisibility('on');
end

end