function layertest()

fig = figure();

ax = axes('parent', fig);
set(ax,...
    'xlim',[-10 10],...
    'xlimmode','manual',...
    'ylim',[-10 10],...
    'ylimmode','manual');

L = RDTools.Layer(ax);
pat = patch(...
    'parent',ax,...
    'xdata',[0 1 1 0],...
    'ydata',[0 0 1 1],...    
    'facecolor',[1 0 0]...
    );
pat2 = patch(...
    'parent',ax,...
    'xdata',[3 3 2 5],...
    'ydata',[6 2 4 5],...    
    'facecolor',[0 1 0]...
    );
L.AddVisual(pat);
L.AddVisual(pat2);

L.SetVisibility('off');
set(L,'name','Shapes');
disp(L);

L2 = RDTools.Layer(ax);
set(L2, 'name','layer 2');

L3 = RDTools.Layer(ax);
set(L3, 'name','layer 3');

layers = [L, L2, L3];
RDTools.gen_layer_menu(layers)

end


